version: '3.7'


services:
   ipfsA:
     image: ipfs/go-ipfs
     container_name: "ipfsA"
     ports:
       - 4001:4001
       - 5001:5001
       - 8080:8080
     volumes:
       - ./ipfsA:/data/ipfs/ 

   clusterA:
     image: ipfs/ipfs-cluster:latest
     container_name: "ipfs-cluster-A"
     environment:
       CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfsA/tcp/5001
       CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
       IPFS_BOOTSTRAP_RM_ALL: "true"
     ports:
       - 127.0.0.1:9094:9094
     depends_on:
       - ipfsA 
     volumes:
       - ./clusterA:/data/ipfs-cluster

   ipfsB:
     image: ipfs/go-ipfs
     container_name: "ipfsB"
     volumes:
       - ./ipfsB:/data/ipfs/
 
   clusterB:
     image: ipfs/ipfs-cluster:latest
     container_name: "ipfs-cluster-B"
     environment:
       CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfsB/tcp/5001
       CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
       IPFS_BOOTSTRAP_RM_ALL: "true"
     depends_on:
       - ipfsB
     volumes:
       - ./clusterB:/data/ipfs-cluster

   ipfsC:
     image: ipfs/go-ipfs
     container_name: "ipfsC"
     volumes:
       - ./ipfsC:/data/ipfs/ 

   clusterC:
     image: ipfs/ipfs-cluster:latest
     container_name: "ipfs-cluster-C"
     environment:
       CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfsC/tcp/5001
       CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
       IPFS_BOOTSTRAP_RM_ALL: "true"
     depends_on:
       - ipfsC
     volumes:
       - ./clusterC:/data/ipfs-cluster
